### ISSUE TITLE
exit() segmentation fault (11)

### ISSUE THREAD

**Issue by ophibox** [preillyme/v8js#135]
I have narrowed down the segfault to the case where you call exit() BEFORE importing a module.
```
[...]
exit();
var foo = require('foo');
[...]
```
which is quite weird as one expects the execution to stop immediately.
Running my tests on an Amazon Linux AMI, php5.4.37 Apache2.4.10
As the script fails, several apache child processes seem to die as well, revealed by apache's error_log :

[core:notice] [pid 1327] AH00052: child pid 20650 exit signal Segmentation fault (11)
[core:notice] [pid 1327] AH00052: child pid 20629 exit signal Segmentation fault (11)
...

**Comment by ophibox** [comment]
just to add to the issue, my setup is looking like this :
```
function __construct(){
   ...
   $this->v8->setModuleLoader([$this,'loadModule']);
}
function loadModule($id)
{
	$f = DB::get()->getFile("jsmod/{$id}.js");
	return $f->content;
}
```

If I purposely add a runtime mistake such as 
```
return $f["content"];
```

There is no more segfault but a fatal error :
```
PHP Fatal error:  Cannot use object of type stdClass as array
PHP Fatal error:  v8::Isolate::Dispose() Disposing the isolate that is entered by a thread. in Unknown on line 0
```

**Comment by stesie** [comment]
Yes!  Nice catch :-) 

V8::TerminateExecution doesn't immediately terminate execution (according to v8 documentation) even so the name might suggest that.  It's thought for terminating long running scripts and hence doesn't need to take effect immediately.

Since v8 itself doesn't provide a means of really terminating execution immediately I've added a work-around to enter an endless loop after signalizing to terminate execution.  This loop usually does a few iterations and finally execution is terminated.

@ophibox could you please try out the patch provided above?  I wrote a little testcase myself and this fixes it.  Please let me know, I'll merge into master then.

cheers
  ~stesie

**Comment by tillz** [comment]
FYI: Same here, in case you need a CoreDump, contact me. I'll try the provided patch.
```
Program received signal SIGSEGV, Segmentation fault.
v8::Object::SetPointerInInternalField (this=0x0, index=0, value=0x159bb88) at ../src/api.cc:3991
```
