### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by xicond** [preillyme/v8js#143]
could this support wss socket ? is this extension available in windows

**Comment by stesie** [comment]
Yes, V8Js can be built on Windows, but it's a bit tedious since V8 as well as V8Js require a c++11 compiler, i.e. Visual Studio 2013 (at least).
However PHP for Windows is compiled with older Visual Studio version, hence you need to compile all the PHP stuff yourself, that you need

See https://github.com/preillyme/v8js/blob/master/README.Win32.md for details

Generally V8Js is a binding of V8 engine to PHP. As such it doesn't expose V8 directly to the network in any way. If you want to expose the V8 JavaScript world to the network, you need to add custom php code providing an API
