### ISSUE TITLE
__call() not supported

### ISSUE THREAD

**Issue by tahpot** [preillyme/v8js#149]
PHP Objects passed to V8 do not support the __call() magic method.

PHP code:
```
class phpObject {
  public function __call($name, $params=[]) {
    return $name;
  }
}
```

Javascript code:
```
// pseudo code
var obj = new PHP.phpObject();
print(obj.helloWorld());
```

Error:
```
V8Js::compileString():3: TypeError: undefined is not a function
```

I also tried obj.$helloWorld(), but that didn't work either.

Calling obj.__call("helloWorld", {}); does work.

**Comment by stesie** [comment]
Yes, you're right.  V8Js behaves exactly as you've pointed out and that's actually expected behaviour (so not well documented).

The "problem" actually is that functions in JavaScript are first class objects, which differs from PHP behaviour.  This is functions are actually plain objects stored in variables.  Hence if you run a method on an object, JavaScript first does a "get" resulting in a function object and then calls that one.
And that's what V8Js actually gets from the V8 API, it first gets a "get" of "helloWorld" (on obj) and possibly a "call" in turn (if it returned a function in the first step).

Sticking to your example it's pretty clear what you'd like to have.
However V8Js doesn't know about the call to come, when the "get" arrives. So if you'd assign `var blar = obj.helloWorld` you wouldn't want `__call` to be called, would you?

Furthermore, enter `__get`, if you have both `__get` and `__call`, which to call when? Keep in mind that V8Js cannot know whether there will be an actual call (immediate or not).

That said, you can go with `__get` like so:

```php
<?php

class Foo {
        function __get($v) {
                echo "__get $v\n";
                        
                if($v == 'blub') {
                        return function() {
                                echo "blub closure called, yippie\n";
                        };
                }

                return 23;
        }
}

$v8 = new \V8Js();
$v8->foo = new \Foo();

$v8->executeString(<<<EOF
  print(PHP.foo.blar + "\\n");
  PHP.foo.blub();
EOF
);
```

which yields

```
__get blar
23
__get blub
blub closure called, yippie
```

This way you even can provide `__call` like behaviour by returning closures bound to the called function name, like so:

```php
<?php

class Foo {
        function __get($v) {
                echo "__get $v\n";
                
                return function() use ($v) {
                        return call_user_func_array(array($this, $v), func_get_args());
                };
        }

        function __call($v, $w) {
                echo "got __call for $v\n";
                var_dump($w);
        }
}

$v8 = new \V8Js();
$v8->foo = new \Foo();

$v8->executeString(<<<EOF
  PHP.foo.blub(23, 42);

  print("if you just get blub, you should see a __get on php side ...\\n");
  var blar = PHP.foo.blub;

  print("... and if you finally call, the call to __call.\\n");
  blar(5);
EOF
);
```

... which yields

```
__get blub
got __call for blub
array(2) {
  [0]=>
  int(23)
  [1]=>
  int(42)
}
if you just get blub, you should see a __get on php side ...
__get blub
... and if you finally call, the call to __call.
got __call for blub
array(1) {
  [0]=>
  int(5)
}
```

hope that helps!

cheers,
  ~stesie

**Comment by tahpot** [comment]
Thanks stesie for the detailed response. That makes perfect sense and gives me a concrete example to work with.

**Comment by rosmo** [comment]
@tahpot, maybe this could help you: http://rosettacode.org/wiki/Respond_to_an_unknown_method_call#JavaScript

**Comment by stesie** [comment]
@rosmo good idea to use ES6 Direct Proxy API

Unfortunately v8 doesn't yet implement it :(

But with an ES6 shim (plus v8 flag `--harmony_proxies`) the code from the referenced page works indeed:

```php
<?php

ini_set("v8js.flags", "--harmony_proxies"); 

$v8 = new V8Js();
$v8->executeString(file_get_contents('https://raw.githubusercontent.com/tvcutsem/harmony-reflect/master/reflect.js'));
$v8->executeString(<<<EOF
    obj = new Proxy({}, 
        { get : function(target, prop) 
            { 
            if(target[prop] === undefined) 
                return function()  {
                print('an otherwise undefined function!!\\n');
                };
            else 
                return target[prop];
            }
        });
    obj.f()        ///'an otherwise undefined function!!'
    obj.l = function() { print(45 + "\\n");};
    obj.l();       ///45
EOF
);
```

applied to the initial question about `__call` behaviour, direct proxy api use could look like:

```php
<?php

ini_set("v8js.flags", "--harmony_proxies");

class Foo {
    function __call($v, $w) {
        echo "got __call for $v\n";
        var_dump($w);
    }
}

$v8 = new V8Js();
$v8->foo = new \Foo();

$v8->executeString(file_get_contents('https://raw.githubusercontent.com/tvcutsem/harmony-reflect/master/reflect.js'));
$v8->executeString(<<<EOF
    var wrapped_foo = new Proxy(PHP.foo,
        { get : function(target, prop)
            {
            if(target[prop] === undefined)
                return function()  {
                    target.__call(prop, arguments);
                };
            else
                return target[prop];
            }
        });
    wrapped_foo.bar(23);
EOF
);
```

**Comment by tahpot** [comment]
Thanks @stesie -- two viable options there.
