### ISSUE TITLE
Recommended V8 version?

### ISSUE THREAD

**Issue by tahpot** [preillyme/v8js#152]
What is the currently recommended V8 version to use?

I tried building the latest on an Amazon AMI and ran into some issues, however specifically requesting 3.32.6 as referenced in README.Linux.md worked fine.

**Comment by tahpot** [comment]
I should also point out the following adjustment to the install instructions which was necessary to get v8js working on the latest AWS AMI:

Change:
```
sudo cp out/native/lib.target/lib*.so /usr/lib/
```
to
```
sudo cp out/native/lib.target/lib*.so /usr/lib64/
```

**Comment by AlexMasterov** [comment]
I managed to get to work only <= 4.5.58 version.

**Comment by stesie** [comment]
@tahpot  the /usr/lib64 thing is distribution dependent, e.g. on Debian there is no such thing as /usr/lib64
But I agree that it's worth mentioning that in `README.Linux.md`

Regarding the V8 version, actually I'd expect every version to function.  The problem is that with 4.4.9 or newer you need to disable snapshot support for V8 to work. If you don't even their example scripts immediately segfault.  This is pass `snapshot=off` to make along `library=shared`, if you use recent V8 version.

Generally you should use pretty new version since they usually just have security support for three minor version lines (that would be 4.4 to 4.6 as of now). So 3.32 might be a bad option.

**Comment by AlexMasterov** [comment]
@stesie after adding `snapshot=off` earned the latest version (4.6.52). Thank you.

**Comment by tahpot** [comment]
Great, thanks for the info.
